[build]
    base = "/"
    command = "npm run build"
    publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"


[[redirects]]
    from = "/_next/static/*"
    to = "/static/:splat"
    status = 301
    force = true

[template.environment]
    OPENAI_API_KEY="Specify your Open AI key"
    MONGODB_ATLAS_URI="Specify your MongoDB Atlas URI"
    MONGODB_DATABASE="The database name (eg. netlify_chat_demo ) "
    MONGODB_SOURCE_COLLECTION="The context collection with embeddings (eg. context)"